# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/sysadminsmedia/homebox:latest"
  amd64: "ghcr.io/sysadminsmedia/homebox:latest"
  armv7: "ghcr.io/sysadminsmedia/homebox:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Homebox"
  org.opencontainers.image.description: "Installs homebox under hassio"
  org.opencontainers.image.source: "https://github.com/home-assistant/addons-example"
  org.opencontainers.image.licenses: ""
args:
  TEMPIO_VERSION: "2021.09.0"
